### ISSUE TITLE
Holograms persist when reloading after modifying config file

### ISSUE THREAD

**Issue by virustotalop** [FancyMcPlugins/FancyHolograms#141] opened 2024-09-14 08:30 UTC
Holograms persist when reloading after modifying the config file.
Steps to reproduce
1. Create a hologram
2. Remove a hologram or update a line for a hologram in the config
3. Run `/fancyholograms reload`

After the reload the old hologram still persists with the old text or the old hologram that was removed from the file.

**Comment by OliverSchlueter** [comment] 2024-11-03 09:45
Duplicate of #125

**Closed by OliverSchlueter** 2024-11-03 09:45 UTC
